site_url: https://maaya.kadobayashi.com
logo_url: https://maaya.kadobayashi.com/images/logo.png
locale: ja
search: false
publish_mode: simple

backend:
  name: github
  repo: maaya-k/blog
  branch: main
  base_url: https://decap.kadobayashi.com

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts・ブログ記事"
    label_singular: "Blog Post・ブログ記事"
    folder: "content/posts"
    create: true
    path: "{{year}}/{{month}}/{{slug}}/index"
    slug: "{{slug}}"
    media_folder: "{{dirname}}"
    public_folder: "{{dirname}}"
    view_filters:
      - label: "Essen・食べ物"
        field: "categories"
        pattern: "Essen・食べ物"
      - label: "Kultur・文化"
        field: "categories"
        pattern: "Kultur・文化"
      - label: "Reisen・旅行"
        field: "categories"
        pattern: "Reisen・旅行"
      - label: "Schule・学校"
        field: "categories"
        pattern: "Schule・学校"
      - label: "Sonstiges・その他"
        field: "categories"
        pattern: "Sonstiges・その他"
      - label: "Draft・下書き"
        field: "draft"
        pattern: true
    view_groups:
      - label: Monat・月
        field: date
        pattern: \d{4}-(\d{2})
    fields:
      - { label: "Titel・タイトル", name: "title", widget: "string" }
      - { label: "Datum・日付", name: "date", widget: "datetime" }
      - { label: "Entwurf・下書き", name: "draft", widget: "boolean", default: true }
      - label: "Kategorie・カテゴリー"
        name: "categories"
        widget: "select"
        options:
          - "Schule・学校"
          - "Reisen・旅行"
          - "Essen・食べ物"
          - "Kultur・文化"
          - "Sonstiges・その他"
      - { label: "Tags・タグ", name: "tags", widget: "list", default: [] }
      - { label: "Inhalt・本文", name: "body", widget: "markdown" }
