site_url: https://maaya.kadobayashi.com
search: false

backend:
  name: github
  repo: maaya-k/blog
  branch: main
  base_url: https://decap.kadobayashi.com

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel・タイトル", name: "title", widget: "string" }
      - { label: "Datum・日付", name: "date", widget: "datetime" }
      - { label: "Entwurf・下書き", name: "draft", widget: "boolean", default: true }
      - label: "Kategorien・カテゴリー"
        name: "categories"
        widget: "list"
        default: []
        field:
          label: "Kategorie・カテゴリー"
          name: "category"
          widget: "select"
          options:
            - { label: "Schule・学校", value: "Schule・学校" }
            - { label: "Reisen・旅行", value: "Reisen・旅行" }
            - { label: "Sonstiges・その他", value: "Sonstiges・その他" }
      - { label: "Tags・タグ", name: "tags", widget: "list", default: [] }
      - { label: "Inhalt・本文", name: "body", widget: "markdown" }
